apiVersion: v1
kind: Secret
metadata:
  name:  postgres-secret
  namespace: ecommerce
  labels:
    env: lab
    app: postgres
type: Opaque
stringData:
  POSTGRES_DB: "ecommercedb"
  POSTGRES_USER: "appuser"
  POSTGRES_PASSWORD: "securepass"