apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: ecommerce
  labels:
    app: redis
    env: lab
spec:
  replicas: 1
  
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  
  selector:
    matchLabels:
      app: redis
  
  template:
    metadata:
      labels:
        app: redis
        env: lab
    
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        imagePullPolicy: IfNotPresent
        
        command:
        - redis-server
        - /usr/local/etc/redis/redis.conf
        
        ports:
        - containerPort: 6379
          name: redis
        
        # SecurityContext
        securityContext:
          runAsNonRoot: true
          runAsUser: 999
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        
        # Volumes
        volumeMounts:
        - name: redis-config
          mountPath: /usr/local/etc/redis
        
        # Resources
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
        
        # Probes
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 5
      
      volumes:
      - name: redis-config
        configMap:
          name: redis-config